import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

plugins {
    id("com.github.ben-manes.versions")
    id("org.jetbrains.kotlinx.kover")
    id("org.sonarqube")

    id("com.android.application") apply false
    id("org.jetbrains.kotlin.android") apply false
}

ext {
    ausweisapp_version = '2.5.4'
    sdkwrapper_version = '2.5.4'
    java_version = 21

    configureRename = { Project module, String suffix ->

        module.tasks.register("renameOutput") {
            dependsOn("assemble")

            doLast {
                def outputDir = module.layout.buildDirectory.dir("outputs/${suffix}").get()
                module.fileTree(outputDir).matching {
                    include("**/*-*.${suffix}")
                    exclude("**/*-*-*.${suffix}")
                }.each { file ->
                    def versionedName = file.name.replace(".${suffix}", "-${sdkwrapper_version}.${suffix}")
                    file.renameTo(new File(file.parent, versionedName))
                }
            }
        }

        module.tasks.named("assemble") {
            finalizedBy("renameOutput")
        }
    }
}

subprojects { subproject ->
    subproject.afterEvaluate {
        tasks.withType(KotlinJvmCompile).configureEach {
            compilerOptions {
                allWarningsAsErrors.set(true)
                freeCompilerArgs.add("-Xstring-concat=inline")
            }
        }
    }
}

sonarqube {
    properties {
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.coverage.jacoco.xmlReportPaths", project.layout.buildDirectory.file("reports/kover/report.xml").get().asFile
    }
}

dependencies {
    kover(project(":sdkwrapper"))
}

allprojects {
    repositories {
        if (System.getenv("MIRROR_GOOGLE_MAVEN")) {
            maven { url = System.getenv("MIRROR_GOOGLE_MAVEN") }
        } else {
            google()
        }
        if (System.getenv("MIRROR_MAVEN")) {
           maven { url = System.getenv("MIRROR_MAVEN") }
        } else {
            mavenCentral()
        }
        maven {
            url = "$project.rootDir/ausweisapp"
        }
    }
}

def isNonStable = { String version ->
    ['alpha', 'beta', 'rc', 'cr', 'm', 'preview', 'b', 'ea', 'dev', 'snapshot'].any { qualifier ->
        version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
    }
}

tasks.named("dependencyUpdates").configure {
    checkForGradleUpdate = false
    outputFormatter = { result ->
        if (!result.outdated.dependencies.isEmpty()) {
            def outdatedLibs = result.outdated.dependencies.collect { dep ->
                " - ${dep.group}:${dep.name} [${dep.version} -> ${dep.available.release ?: dep.available.milestone}]"
            }.join('\n')

            throw new GradleException("Build failed! The following outdated dependencies were found:\n$outdatedLibs")
        } else {
            println "All dependencies are up to date."
        }
    }
    rejectVersionIf { selection ->
        if (selection.candidate.group == "androidx.core" && selection.candidate.module == "core-ktx") {
            if (selection.candidate.version == "1.19.0") {
                return true // Requires Gradle upgrade incompatible with SonarQube plugin
            }
        }
        if (selection.candidate.group == "com.android.application" && selection.candidate.module == "com.android.application.gradle.plugin") {
            if (selection.candidate.version in ["9.0.0", "9.0.1", "9.1.0", "9.1.1", "9.2.0", "9.2.1"]) {
                return true // Requires Gradle upgrade incompatible with SonarQube plugin
            }
        }
        if (selection.candidate.group == "androidx.databinding" && selection.candidate.module == "viewbinding") {
            if (selection.candidate.version in ["9.0.0", "9.0.1", "9.1.0", "9.1.1", "9.2.0", "9.2.1"]) {
                return true // Requires Gradle upgrade incompatible with SonarQube plugin
            }
        }
        if (selection.candidate.group == "org.jetbrains.kotlin" || selection.candidate.group == "org.jetbrains.kotlin.android") {
            if (selection.candidate.version == "2.4.10") {
                return true // Needed because there seems to be a transitive dependency on 2.4.0 somewhere, which currently cannot be updated
            }
            if (isNonStable(selection.candidate.version)) {
                return true // Needed because the beta versions show up as false positives even when the stable version 2.4.0 is used
            }
        }
        if (selection.candidate.group == "com.google.testing.platform") {
            return true // Transitive dependency managed by Android Gradle Plugin
        }
        if (selection.candidate.group == "com.android.tools.utp") {
            return true // Transitive dependency managed by Android Gradle Plugin
        }

        if (isNonStable(selection.candidate.version) && !isNonStable(selection.currentVersion)) {
            return true
        }
        return false
    }
}

tasks.register("tarball", Tar) {
    into ('/') {
        from rootDir
        include '**'
        exclude ('dist', '**/build/**', '.reviewboardrc', '.gradle', '.idea', '**/*.aar', '**/*.apk')
     }

    archiveFileName = "SDKWrapper-Android-Sources.tgz"
    destinationDirectory = file('build/tar')
    compression = Compression.GZIP
}
